version: 0.5.{build}
image: 
  - Ubuntu2004
  - Visual Studio 2019
  - Visual Studio 2022

environment:
  platform: x64
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  matrix:
  - cmake_options: -DUSE_SDL_INSTEADOF_SFML=OFF
  - cmake_options: -DUSE_SDL_INSTEADOF_SFML=ON

for:
-
  # Windows
  matrix:
    only:
    - image: Visual Studio 2019
    - image: Visual Studio 2022

  install:
  - pip install conan

  build_script:
  - mkdir out && cd out
  - cmake -DCMAKE_BUILD_TYPE=%Configuration% %cmake_options% ..

-
  # Ubuntu
  matrix:
    only:
    - image: Ubuntu2004

  install:
  - sudo apt purge -y --allow-change-held-packages mssql-server
  - sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
  - sudo apt-get -y install clang-13 libc++-13-dev libc++abi-13-dev
#  - sudo apt-get -y upgrade clang

  - sudo apt-get -y install libgl-dev
  - source $HOME/venv3.9/bin/activate
  - pip install --upgrade pip
  - pip install conan

  build_script:
  - mkdir out && cd out
  - export CC=/usr/bin/clang-13
  - export CXX=/usr/bin/clang++-13
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-stdlib=libc++" %cmake_options% ..
  - make