version: 0.5.{build}
image: 
  - Ubuntu2004
  - Visual Studio 2019
  - Visual Studio 2022

environment:
  platform: x64
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

for:
-
  # Windows
  matrix:
    only:
    - image: Visual Studio 2019
    - image: Visual Studio 2022

  install:
  - pip install conan

  build_script:
  - mkdir out && cd out
  - cmake -DCMAKE_BUILD_TYPE=%Configuration% ..

-
  # Ubuntu
  matrix:
    only:
    - image: Ubuntu2004

  install:
  - sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
  - sudo apt-get update
  - sudo apt-get -y install clang-format clang-tidy clang-tools clang clangd libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1 liblldb-dev libllvm-ocaml-dev libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm python-clang 
  - sudo apt-get -y install libc++-13-dev libc++abi-13-dev
#  - sudo apt-get upgrade clang

  - sudo apt-get -y install libgl-dev
  - source $HOME/venv3.9/bin/activate
  - pip install --upgrade pip
  - pip install conan

  build_script:
  - mkdir out && cd out
  - export CC=/usr/bin/clang-13
  - export CXX=/usr/bin/clang++-13
  - cmake -DCMAKE_BUILD_TYPE=Debug -CMAKE_CXX_FLAGS="-stdlib=libc++" ..
  - make